name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: phpunit
      run: |
        alias phpunit="../vendor/phpunit/phpunit/phpunit"
        phpunit tests/ 
  
  deploy:
    
    runs-on: ubuntu-latest
    needs: build
    # if: github.event == 'push'

    steps:
    - uses: actions/checkout@v2
    
    - name: GitHub Event Check
      run: cat $GITHUB_EVENT

    # - name: Install SSH key
    #   uses: shimataro/ssh-key-action@v1
    #   with: # shimataro/ssh-key-actionに渡すパラメーター
    #     private-key: ${{ secrets.SSH_KEY }} 
    #     public-key: ${{ secrets.SSH_KEY_PUBLIC }} 
    #     name: ed25519
    #     known-hosts: ${{ secrets.KNOWN_HOSTS }} 

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: ssh
      run: |
        ssh -vvv $HOSTNAME
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -t -t $LOGINUSER@$HOSTNAME -p $PORT
      env: 
        HOSTNAME: ${{ secrets.HOSTNAME }}
        LOGINUSER: ${{ secrets.LOGINUSER }}
        PORT: ${{ secrets.PORT }}
        PRIVATE_KEY: ${{ secrets.SSH_KEY }} 

    - name: deploy
      run: |
        ./vendor/bin/dep deploy production -vvv
      env: 
        HOSTNAME: ${{ secrets.HOSTNAME }}
        LOGINUSER: ${{ secrets.LOGINUSER }}
        PORT: ${{ secrets.PORT }}

